班級:財金三乙
姓名:林晏靚
學號:A105040092

# A.regression
# from sklearn.preprocessing import PolynomialFeatures
# PolynomialFeatures(degree=3, include_bias=True)
# 40462.09922679004

# B.Classification
# bag_clf=BaggingClassifier(DecisionTreeClassifier(),n_estimators=500,max_samples=100,bootstrap=True,n_jobs=-1)
# 0.8931686046511628

In [1]:
import pandas as pd
import numpy as np

In [2]:
housing = pd.read_csv("housing.csv")

In [3]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
5        -122.25     37.85                52.0        919.0           213.0   
6        -122.25     37.84                52.0       2535.0           489.0   
7        -122.25     37.84                52.0       3104.0           687.0   
8        -122.26     37.84                42.0       2555.0           665.0   
9        -122.25     37.84                52.0       3549.0           707.0   
10       -122.26     37.85                52.0       2202.0           434.0   
11       -122.26     37.85                52.0       3503.0           752.0   
12       -122.26     37.85                52.0       2491.0           474.0   
13       -122.26     37.84                52.0        696.0           191.0   
14       -122.26     37.85                52.0       2643.0           626.0   
15       -122.26     37.85                50.0       1120.0           283.0   
16       -122.27     37.85                52.0       1966.0           347.0   
17       -122.27     37.85                52.0       1228.0           293.0   
18       -122.26     37.84                50.0       2239.0           455.0   
19       -122.27     37.84                52.0       1503.0           298.0   
20       -122.27     37.85                40.0        751.0           184.0   
21       -122.27     37.85                42.0       1639.0           367.0   
22       -122.27     37.84                52.0       2436.0           541.0   
23       -122.27     37.84                52.0       1688.0           337.0   
24       -122.27     37.84                52.0       2224.0           437.0   
25       -122.28     37.85                41.0        535.0           123.0   
26       -122.28     37.85                49.0       1130.0           244.0   
27       -122.28     37.85                52.0       1898.0           421.0   
28       -122.28     37.84                50.0       2082.0           492.0   
29       -122.28     37.84                52.0        729.0           160.0   
...          ...       ...                 ...          ...             ...   
20610    -121.56     39.10                28.0       2130.0           484.0   
20611    -121.55     39.10                27.0       1783.0           441.0   
20612    -121.56     39.08                26.0       1377.0           289.0   
20613    -121.55     39.09                31.0       1728.0           365.0   
20614    -121.54     39.08                26.0       2276.0           460.0   
20615    -121.54     39.08                23.0       1076.0           216.0   
20616    -121.53     39.08                15.0       1810.0           441.0   
20617    -121.53     39.06                20.0        561.0           109.0   
20618    -121.55     39.06                25.0       1332.0           247.0   
20619    -121.56     39.01                22.0       1891.0           340.0   
20620    -121.48     39.05                40.0        198.0            41.0   
20621    -121.47     39.01                37.0       1244.0           247.0   
20622    -121.44     39.00                20.0        755.0           147.0   
20623    -121.37     39.03                32.0       1158.0           244.0   
20624    -121.41     39.04                16.0       1698.0           300.0   
20625    -121.52     39.12                37.0        102.0            17.0   
20626    -121.43     39.18                36.0       1124.0           184.0   
20627    -121.32     39.13                 5.0        358.0            65.0   
20628    -121.48     39.10                19.0       2043

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20640 non-null float64
latitude              20640 non-null float64
housing_median_age    20640 non-null float64
total_rooms           20640 non-null float64
total_bedrooms        20433 non-null float64
population            20640 non-null float64
households            20640 non-null float64
median_income         20640 non-null float64
median_house_value    20640 non-null float64
ocean_proximity       20640 non-null object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [5]:
housing[housing.isnull().any(axis=1)]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
290      -122.16     37.77                47.0       1256.0             NaN   
341      -122.17     37.75                38.0        992.0             NaN   
538      -122.28     37.78                29.0       5154.0             NaN   
563      -122.24     37.75                45.0        891.0             NaN   
696      -122.10     37.69                41.0        746.0             NaN   
738      -122.14     37.67                37.0       3342.0             NaN   
1097     -121.77     39.66                20.0       3759.0             NaN   
1350     -121.95     38.03                 5.0       5526.0             NaN   
1456     -121.98     37.96                22.0       2987.0             NaN   
1493     -122.01     37.94                23.0       3741.0             NaN   
1606     -122.08     37.88                26.0       2947.0             NaN   
2028     -119.75     36.71                38.0       1481.0             NaN   
2115     -119.72     36.76                23.0       6403.0             NaN   
2301     -119.78     36.82                25.0       5016.0             NaN   
2323     -119.73     36.83                 8.0       3602.0             NaN   
2334     -119.69     36.83                32.0       1098.0             NaN   
2351     -119.68     36.79                16.0       1551.0             NaN   
2412     -119.45     36.61                24.0       1302.0             NaN   
2420     -119.44     36.58                37.0       1054.0             NaN   
2578     -124.06     40.86                34.0       4183.0             NaN   
2608     -124.00     40.92                29.0       1429.0             NaN   
2647     -124.13     40.55                38.0        544.0             NaN   
2826     -119.11     35.42                52.0        154.0             NaN   
3024     -119.46     35.14                30.0       2943.0             NaN   
3328     -122.72     38.88                29.0       2781.0             NaN   
3354     -120.67     40.50                15.0       5343.0             NaN   
3376     -118.28     34.25                29.0       2559.0             NaN   
3482     -118.45     34.30                27.0       2676.0             NaN   
3485     -118.55     34.28                16.0       8879.0             NaN   
3529     -118.53     34.26                18.0       3674.0             NaN   
...          ...       ...                 ...          ...             ...   
18466    -121.75     37.11                18.0       3167.0             NaN   
18786    -122.42     40.44                16.0        994.0             NaN   
18873    -122.22     38.08                37.0       2811.0             NaN   
18914    -122.22     38.15                 7.0       5129.0             NaN   
19060    -122.41     38.16                37.0       1549.0             NaN   
19071    -122.53     38.32                22.0       3577.0             NaN   
19122    -122.65     38.25                23.0       4030.0             NaN   
19150    -122.70     38.35                14.0       2313.0             NaN   
19252    -122.79     38.48                 7.0       6837.0             NaN   
19332    -122.91     38.46                18.0       2021.0             NaN   
19391    -120.85     37.78                25.0        421.0             NaN   
19402    -120.93     37.73                14.0       2799.0             NaN   
19485    -120.98     37.66                10.0        934.0             NaN   
19559    -120.98     37.60                36.0       1437.0             NaN   
19607    -121.02     37.48                26.0        467.0             NaN   
19638    -120.97     37.43                27.0       1380.0             NaN   
19766    -122.10     40.03                25.0       2516.0             NaN   
19818    -119.30     36.57                32.0        728.0             NaN   
19833    -119.38     36.53                38.0       1281

In [6]:
housing = housing.drop("total_bedrooms", axis=1)

In [7]:
housing.head()

longitude  latitude  housing_median_age  total_rooms  population  \
0    -122.23     37.88                41.0        880.0       322.0   
1    -122.22     37.86                21.0       7099.0      2401.0   
2    -122.24     37.85                52.0       1467.0       496.0   
3    -122.25     37.85                52.0       1274.0       558.0   
4    -122.25     37.85                52.0       1627.0       565.0   

   households  median_income  median_house_value ocean_proximity  
0       126.0         8.3252            452600.0        NEAR BAY  
1      1138.0         8.3014            358500.0        NEAR BAY  
2       177.0         7.2574            352100.0        NEAR BAY  
3       219.0         5.6431            341300.0        NEAR BAY  
4       259.0         3.8462            342200.0        NEAR BAY

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [9]:
housing_cat = housing["ocean_proximity"]

In [10]:
housing_cat_encoded = encoder.fit_transform(housing_cat)

In [11]:

housing_cat_encoded

array([3, 3, 3, ..., 1, 1, 1])

In [12]:
type(housing_cat_encoded)

numpy.ndarray

In [13]:
housing_cat_encoded.shape

(20640,)

In [14]:
pd.DataFrame(housing_cat_encoded)

0
0      3
1      3
2      3
3      3
4      3
5      3
6      3
7      3
8      3
9      3
10     3
11     3
12     3
13     3
14     3
15     3
16     3
17     3
18     3
19     3
20     3
21     3
22     3
23     3
24     3
25     3
26     3
27     3
28     3
29     3
...   ..
20610  1
20611  1
20612  1
20613  1
20614  1
20615  1
20616  1
20617  1
20618  1
20619  1
20620  1
20621  1
20622  1
20623  1
20624  1
20625  1
20626  1
20627  1
20628  1
20629  1
20630  1
20631  1
20632  1
20633  1
20634  1
20635  1
20636  1
20637  1
20638  1
20639  1

[20640 rows x 1 columns]

In [15]:
housing_cat_encoded.reshape(-1, 1)

array([[3],
       [3],
       [3],
       ...,
       [1],
       [1],
       [1]])

In [16]:
housing_cat_encoded.reshape(-1, 1).shape

(20640, 1)

In [17]:
pd.DataFrame(housing_cat_encoded.reshape(-1, 1))

0
0      3
1      3
2      3
3      3
4      3
5      3
6      3
7      3
8      3
9      3
10     3
11     3
12     3
13     3
14     3
15     3
16     3
17     3
18     3
19     3
20     3
21     3
22     3
23     3
24     3
25     3
26     3
27     3
28     3
29     3
...   ..
20610  1
20611  1
20612  1
20613  1
20614  1
20615  1
20616  1
20617  1
20618  1
20619  1
20620  1
20621  1
20622  1
20623  1
20624  1
20625  1
20626  1
20627  1
20628  1
20629  1
20630  1
20631  1
20632  1
20633  1
20634  1
20635  1
20636  1
20637  1
20638  1
20639  1

[20640 rows x 1 columns]

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
encoder = OneHotEncoder(categories='auto')
housing_cat_1hot = encoder.fit_transform(housing_cat_encoded.reshape(-1,1))

In [20]:

housing_cat_1hot

<20640x5 sparse matrix of type '<class 'numpy.float64'>'
	with 20640 stored elements in Compressed Sparse Row format>

In [21]:
housing_cat_1hot.toarray()

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [22]:
pd.DataFrame(housing_cat_1hot.toarray())

0    1    2    3    4
0      0.0  0.0  0.0  1.0  0.0
1      0.0  0.0  0.0  1.0  0.0
2      0.0  0.0  0.0  1.0  0.0
3      0.0  0.0  0.0  1.0  0.0
4      0.0  0.0  0.0  1.0  0.0
5      0.0  0.0  0.0  1.0  0.0
6      0.0  0.0  0.0  1.0  0.0
7      0.0  0.0  0.0  1.0  0.0
8      0.0  0.0  0.0  1.0  0.0
9      0.0  0.0  0.0  1.0  0.0
10     0.0  0.0  0.0  1.0  0.0
11     0.0  0.0  0.0  1.0  0.0
12     0.0  0.0  0.0  1.0  0.0
13     0.0  0.0  0.0  1.0  0.0
14     0.0  0.0  0.0  1.0  0.0
15     0.0  0.0  0.0  1.0  0.0
16     0.0  0.0  0.0  1.0  0.0
17     0.0  0.0  0.0  1.0  0.0
18     0.0  0.0  0.0  1.0  0.0
19     0.0  0.0  0.0  1.0  0.0
20     0.0  0.0  0.0  1.0  0.0
21     0.0  0.0  0.0  1.0  0.0
22     0.0  0.0  0.0  1.0  0.0
23     0.0  0.0  0.0  1.0  0.0
24     0.0  0.0  0.0  1.0  0.0
25     0.0  0.0  0.0  1.0  0.0
26     0.0  0.0  0.0  1.0  0.0
27     0.0  0.0  0.0  1.0  0.0
28     0.0  0.0  0.0  1.0  0.0
29     0.0  0.0  0.0  1.0  0.0
...    ...  ...  ...  ...  ...
20610  0.0  1.0  0.0  0.0  0.0
20611  0.0  1.0  0.0  0.0  0.0
20612  0.0  1.0  0.0  0.0  0.0
20613  0.0  1.0  0.0  0.0  0.0
20614  0.0  1.0  0.0  0.0  0.0
20615  0.0  1.0  0.0  0.0  0.0
20616  0.0  1.0  0.0  0.0  0.0
20617  0.0  1.0  0.0  0.0  0.0
20618  0.0  1.0  0.0  0.0  0.0
20619  0.0  1.0  0.0  0.0  0.0
20620  0.0  1.0  0.0  0.0  0.0
20621  0.0  1.0  0.0  0.0  0.0
20622  0.0  1.0  0.0  0.0  0.0
20623  0.0  1.0  0.0  0.0  0.0
20624  0.0  1.0  0.0  0.0  0.0
20625  0.0  1.0  0.0  0.0  0.0
20626  0.0  1.0  0.0  0.0  0.0
20627  0.0  1.0  0.0  0.0  0.0
20628  0.0  1.0  0.0  0.0  0.0
20629  0.0  1.0  0.0  0.0  0.0
20630  0.0  1.0  0.0  0.0  0.0
20631  0.0  1.0  0.0  0.0  0.0
20632  0.0  1.0  0.0  0.0  0.0
20633  0.0  1.0  0.0  0.0  0.0
20634  0.0  1.0  0.0  0.0  0.0
20635  0.0  1.0  0.0  0.0  0.0
20636  0.0  1.0  0.0  0.0  0.0
20637  0.0  1.0  0.0  0.0  0.0
20638  0.0  1.0  0.0  0.0  0.0
20639  0.0  1.0  0.0  0.0  0.0

[20640 rows x 5 columns]

In [23]:
housing.head()

longitude  latitude  housing_median_age  total_rooms  population  \
0    -122.23     37.88                41.0        880.0       322.0   
1    -122.22     37.86                21.0       7099.0      2401.0   
2    -122.24     37.85                52.0       1467.0       496.0   
3    -122.25     37.85                52.0       1274.0       558.0   
4    -122.25     37.85                52.0       1627.0       565.0   

   households  median_income  median_house_value ocean_proximity  
0       126.0         8.3252            452600.0        NEAR BAY  
1      1138.0         8.3014            358500.0        NEAR BAY  
2       177.0         7.2574            352100.0        NEAR BAY  
3       219.0         5.6431            341300.0        NEAR BAY  
4       259.0         3.8462            342200.0        NEAR BAY

In [24]:
pd.DataFrame(housing_cat_1hot.toarray()).iloc[:, 1:].head()

1    2    3    4
0  0.0  0.0  1.0  0.0
1  0.0  0.0  1.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  1.0  0.0
4  0.0  0.0  1.0  0.0

In [25]:
housing_final = pd.concat([housing, pd.DataFrame(housing_cat_1hot.toarray()).iloc[:, 1:]], axis=1)

In [26]:
housing_final.head()

longitude  latitude  housing_median_age  total_rooms  population  \
0    -122.23     37.88                41.0        880.0       322.0   
1    -122.22     37.86                21.0       7099.0      2401.0   
2    -122.24     37.85                52.0       1467.0       496.0   
3    -122.25     37.85                52.0       1274.0       558.0   
4    -122.25     37.85                52.0       1627.0       565.0   

   households  median_income  median_house_value ocean_proximity    1    2  \
0       126.0         8.3252            452600.0        NEAR BAY  0.0  0.0   
1      1138.0         8.3014            358500.0        NEAR BAY  0.0  0.0   
2       177.0         7.2574            352100.0        NEAR BAY  0.0  0.0   
3       219.0         5.6431            341300.0        NEAR BAY  0.0  0.0   
4       259.0         3.8462            342200.0        NEAR BAY  0.0  0.0   

     3    4  
0  1.0  0.0  
1  1.0  0.0  
2  1.0  0.0  
3  1.0  0.0  
4  1.0  0.0

In [27]:
X = housing_final.drop("median_house_value", axis=1).drop("ocean_proximity", axis=1)

In [28]:
X.head()

longitude  latitude  housing_median_age  total_rooms  population  \
0    -122.23     37.88                41.0        880.0       322.0   
1    -122.22     37.86                21.0       7099.0      2401.0   
2    -122.24     37.85                52.0       1467.0       496.0   
3    -122.25     37.85                52.0       1274.0       558.0   
4    -122.25     37.85                52.0       1627.0       565.0   

   households  median_income    1    2    3    4  
0       126.0         8.3252  0.0  0.0  1.0  0.0  
1      1138.0         8.3014  0.0  0.0  1.0  0.0  
2       177.0         7.2574  0.0  0.0  1.0  0.0  
3       219.0         5.6431  0.0  0.0  1.0  0.0  
4       259.0         3.8462  0.0  0.0  1.0  0.0

In [29]:
y = housing_final[["median_house_value"]]
y.head()

median_house_value
0            452600.0
1            358500.0
2            352100.0
3            341300.0
4            342200.0

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [31]:

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [41]:
lin_reg.predict(X_train)

array([[152870.61204644],
       [272288.07782461],
       [221986.66476428],
       ...,
       [254430.34184398],
       [309772.53494212],
       [ 28074.25200439]])

In [42]:

from sklearn.metrics import mean_squared_error

housing_predictions = lin_reg.predict(X_train)
lin_mse = mean_squared_error(y_train, housing_predictions)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

from sklearn.metrics import mean_absolute_error
lin_mae = mean_absolute_error(y_train, housing_predictions)
print(lin_mae)

68935.96791365546
50168.91304150329


In [43]:

from sklearn.metrics import mean_squared_error

housing_predictions = lin_reg.predict(X_test)
lin_mse = mean_squared_error(y_test, housing_predictions)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

from sklearn.metrics import mean_absolute_error
lin_mae = mean_absolute_error(y_test, housing_predictions)
print(lin_mae)

69028.13810328285
50027.82027432185


In [44]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [45]:
lin_reg.intercept_

array([-2168249.37134475])

In [46]:
lin_reg.coef_

array([[-2.58177483e+04, -2.47894826e+04,  1.05316186e+03,
        -3.91802106e-02, -4.12735805e+01,  1.34852434e+02,
         3.75285224e+04, -3.98508652e+04,  1.65725840e+05,
        -3.68208429e+03,  5.75815333e+03]])

In [47]:
lin_reg.predict(X_test)

array([[216747.97228902],
       [291470.65775078],
       [180910.66779174],
       ...,
       [ 91051.93602541],
       [254964.77292657],
       [211769.51349345]])

In [92]:

from sklearn.preprocessing import PolynomialFeatures

In [93]:
poly_features = PolynomialFeatures(degree=3, include_bias=True)

In [94]:
X_poly = poly_features.fit_transform(X_train)

In [95]:
X_poly.shape

(16512, 364)

In [96]:
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [97]:
housing_predictions = lin_reg.predict(X_poly)

In [98]:
housing_predictions.shape

(16512, 1)

In [99]:
y_train.shape

(16512, 1)

In [100]:
from sklearn.metrics import mean_squared_error

housing_predictions = lin_reg.predict(X_poly)
lin_mse = mean_squared_error(y_train, housing_predictions)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

from sklearn.metrics import mean_absolute_error
lin_mae = mean_absolute_error(y_train, housing_predictions)
print(lin_mae)

56557.51636692046
39411.98428288124


In [101]:
X_test.shape

(4128, 11)

In [102]:
X_poly_test = poly_features.fit_transform(X_test)

In [103]:
X_poly_test.shape

(4128, 364)

In [104]:
from sklearn.metrics import mean_squared_error

housing_predictions = lin_reg.predict(X_poly_test)
lin_mse = mean_squared_error(y_test, housing_predictions)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

from sklearn.metrics import mean_absolute_error
lin_mae = mean_absolute_error(y_test, housing_predictions)
print(lin_mae)

62767.47064105413
40462.09922679004


In [32]:
from sklearn.linear_model import ElasticNet

In [91]:
elastic_net=ElasticNet(alpha=0.1,l1_ratio=0.5)

In [34]:
elastic_net.fit(X_train,y_train)

ElasticNet(alpha=0.1, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [35]:
elastic_net.predict(X_test)

array([215259.15789615, 289816.19339796, 184700.32170715, ...,
        95110.3018028 , 257023.13191423, 211505.16650059])

In [36]:
from sklearn.metrics import mean_squared_error

housing_predictions = elastic_net.predict(X_test)
ela_mse = mean_squared_error(y_test, housing_predictions)
ela_rmse = np.sqrt(ela_mse)
print(ela_rmse)

from sklearn.metrics import mean_absolute_error
ela_mae = mean_absolute_error(y_test, housing_predictions)
print(ela_mae)

69268.74824254078
50221.44374249095


In [75]:
from sklearn.tree import DecisionTreeRegressor

In [76]:
tree_reg=DecisionTreeRegressor(max_depth=2)

In [77]:
tree_reg.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=2, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [81]:
from sklearn.linear_model import Lasso

In [86]:
lasso_reg=Lasso(alpha=1)

In [87]:
lasso_reg.fit(X_train,y_train)

Lasso(alpha=1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [88]:
lasso_reg.predict(X_test)

array([216743.60025723, 291471.64046972, 180909.81853492, ...,
        91051.04660157, 254963.74513395, 211771.81184605])

In [89]:
from sklearn.metrics import mean_squared_error

housing_predictions = lasso_reg.predict(X_test)
las_mse = mean_squared_error(y_test, housing_predictions)
las_rmse = np.sqrt(las_mse)
print(las_rmse)

from sklearn.metrics import mean_absolute_error
las_mae = mean_absolute_error(y_test, housing_predictions)
print(las_mae)

69027.88557271037
50028.17282885785


分類

In [58]:
import copy

In [59]:
housing_classify = copy.deepcopy(housing_final)
housing_classify.head(10)

longitude  latitude  housing_median_age  total_rooms  population  \
0    -122.23     37.88                41.0        880.0       322.0   
1    -122.22     37.86                21.0       7099.0      2401.0   
2    -122.24     37.85                52.0       1467.0       496.0   
3    -122.25     37.85                52.0       1274.0       558.0   
4    -122.25     37.85                52.0       1627.0       565.0   
5    -122.25     37.85                52.0        919.0       413.0   
6    -122.25     37.84                52.0       2535.0      1094.0   
7    -122.25     37.84                52.0       3104.0      1157.0   
8    -122.26     37.84                42.0       2555.0      1206.0   
9    -122.25     37.84                52.0       3549.0      1551.0   

   households  median_income  median_house_value ocean_proximity    1    2  \
0       126.0         8.3252            452600.0        NEAR BAY  0.0  0.0   
1      1138.0         8.3014            358500.0        NEAR BAY  0.0  0.0   
2       177.0         7.2574            352100.0        NEAR BAY  0.0  0.0   
3       219.0         5.6431            341300.0        NEAR BAY  0.0  0.0   
4       259.0         3.8462            342200.0        NEAR BAY  0.0  0.0   
5       193.0         4.0368            269700.0        NEAR BAY  0.0  0.0   
6       514.0         3.6591            299200.0        NEAR BAY  0.0  0.0   
7       647.0         3.1200            241400.0        NEAR BAY  0.0  0.0   
8       595.0         2.0804            226700.0        NEAR BAY  0.0  0.0   
9       714.0         3.6912            261100.0        NEAR BAY  0.0  0.0   

     3    4  
0  1.0  0.0  
1  1.0  0.0  
2  1.0  0.0  
3  1.0  0.0  
4  1.0  0.0  
5  1.0  0.0  
6  1.0  0.0  
7  1.0  0.0  
8  1.0  0.0  
9  1.0  0.0

In [60]:
housing_classify["median_house_value"].median()

179700.0

In [61]:
housing_classify['midian_classify'] = housing_classify["median_house_value"]> housing_classify["median_house_value"].median()
housing_classify['midian_classify'].head(10)

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: midian_classify, dtype: bool

In [62]:
housing_classify['midian_classify'] = housing_classify['midian_classify'].astype(int)
housing_classify['midian_classify'].head(10)

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: midian_classify, dtype: int32

In [63]:
X = housing_classify.drop("median_house_value", axis=1).drop("ocean_proximity", axis=1).drop("midian_classify", axis=1)

In [64]:
X.head()

longitude  latitude  housing_median_age  total_rooms  population  \
0    -122.23     37.88                41.0        880.0       322.0   
1    -122.22     37.86                21.0       7099.0      2401.0   
2    -122.24     37.85                52.0       1467.0       496.0   
3    -122.25     37.85                52.0       1274.0       558.0   
4    -122.25     37.85                52.0       1627.0       565.0   

   households  median_income    1    2    3    4  
0       126.0         8.3252  0.0  0.0  1.0  0.0  
1      1138.0         8.3014  0.0  0.0  1.0  0.0  
2       177.0         7.2574  0.0  0.0  1.0  0.0  
3       219.0         5.6431  0.0  0.0  1.0  0.0  
4       259.0         3.8462  0.0  0.0  1.0  0.0

In [65]:
y = housing_classify[["midian_classify"]]
y.head()

midian_classify
0                1
1                1
2                1
3                1
4                1

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [67]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\USER\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [68]:
# train performance
y_pred = log_reg.predict(X_train)
n_correct = sum(y_pred == y_train.as_matrix().ravel())
print(n_correct / len(y_pred))
# test performance
y_pred = log_reg.predict(X_test)
n_correct = sum(y_pred == y_test.as_matrix().ravel())
print(n_correct / len(y_pred))

0.8272771317829457
0.8238856589147286


C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [69]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

In [70]:
from sklearn.datasets import make_moons
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
polynomial_svm_clf = Pipeline([
 ("poly_features", PolynomialFeatures(degree=3)),
 ("scaler", StandardScaler()),
 ("svm_clf", LinearSVC(C=10, loss="hinge"))
 ])
polynomial_svm_clf.fit(X, y)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\USER\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Pipeline(memory=None,
     steps=[('poly_features', PolynomialFeatures(degree=3, include_bias=True, interaction_only=False)), ('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('svm_clf', LinearSVC(C=10, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0))])

In [71]:
# train performance
y_pred = polynomial_svm_clf.predict(X_train)
n_correct = sum(y_pred == y_train.as_matrix().ravel())
print(n_correct / len(y_pred))
# test performance
y_pred = polynomial_svm_clf.predict(X_test)
n_correct = sum(y_pred == y_test.as_matrix().ravel())
print(n_correct / len(y_pred))

0.8495033914728682
0.8471414728682171


C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [72]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [73]:
bag_clf=BaggingClassifier(DecisionTreeClassifier(),n_estimators=500,max_samples=100,bootstrap=True,n_jobs=-1)
bag_clf.fit(X_train,y_train)
y_pred=bag_clf.predict(X_train)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:622: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [74]:
bag_clf=BaggingClassifier(DecisionTreeClassifier(),n_estimators=500,oob_score=True,bootstrap=True,n_jobs=-1)

In [75]:
bag_clf.fit(X_train,y_train)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:622: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=500, n_jobs=-1, oob_score=True,
         random_state=None, verbose=0, warm_start=False)

In [76]:
bag_clf.oob_score_

0.8943192829457365

In [77]:
from sklearn.metrics import accuracy_score

In [78]:
y_pred=bag_clf.predict(X_test)

In [79]:
accuracy_score(y_test,y_pred)

0.8929263565891473